apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 8080      # The port that will be exposed externally
      targetPort: 8080  # The port on the apigateway container
  type: LoadBalancer  # Exposes the service externally using the Azure's load balancer
  

